### ISSUE TITLE
请问你的Y470驱动用什么工具安装？

### ISSUE THREAD

**Issue by vdeng-ai** [Dwarven/Hackintosh#1]
你好，我看到你的Y470驱动配置文件，就把自己的笔记本也装了黑苹果，但是现在系统装好了，可是不知道如何使用你的驱动，远景论坛也无法打开，能不能麻烦你抽空告知，谢谢！

**Comment by Dwarven** [comment]
放Clover的驱动目录里就行啊，放到kexts下对应的系统版本文件夹或者Other文件夹里
![image](https://user-images.githubusercontent.com/5902224/35325579-2663852c-012f-11e8-8af2-1d4dfca07ac7.png)
